### ISSUE TITLE
红米k30无法工作

### ISSUE THREAD

**Issue by TypeThe0ry** [Sab1e-GitHub/BadAppleJuice#1]
在红米k30上使用，苹果手机蓝牙打开的情况下，没有任何效果

**Comment by Sab1e-dev** [comment]
如果您的设备能够正常显示“正在发送广播包……”，但广播没有效果，我认为有两种可能：
第一种原因可能是您设备的Android版本问题，我查询到红米K30的Android版本为Android 10，此项目minSdk = 31，也就是说最低安卓版本为Android 12。针对此问题我抽空会重新移植一下，降低SDK版本来适应更多的设备。目前您可以尝试在更高安卓版本的设备上测试使用。
第二种原因，经过本人测试，可能目前广播包发送设备必须距离接收设备（苹果手机）非常近才能接收到广播，具体原因尚不清楚，本人会继续测试以解决此问题。
最后，感谢您提交的issue以帮助此项目继续改进。
