### ISSUE TITLE
华为EMUI11解析包错误

### ISSUE THREAD

**Issue by GaoZx13470** [Sab1e-GitHub/BadAppleJuice#2]
![Screenshot_20231124_235341_com android packageinstaller](https://github.com/Sab1e-GitHub/BadAppleJuice/assets/67144284/316dbc42-3efd-45c9-b50c-eae7efb450a1)
华为EMUI11解析包错误，无法安装！
用mt重新签名依然不好使，不太会安卓的东西，麻烦解决一下！

**Comment by Sab1e-dev** [comment]
据我所查询到的资料显示，EMUI11的安卓版本应该是Android10，与本软件的SDK版本不一致，这个问题跟Issue#1里提到的版本问题相同，详细信息可以去看Issue#1。
下一版本将会降低SDK，以支持更多设备。
感谢您提出的Issue以帮助此项目改进。
