### ISSUE TITLE
小米8 安卓9无法工作

### ISSUE THREAD

**Issue by zR00t1** [Sab1e-GitHub/BadAppleJuice#3]
### 授予蓝牙权限后仍然弹窗提示程序需要获取权限！

![image](https://github.com/Sab1e-GitHub/BadAppleJuice/assets/46400438/57a990de-fb04-438b-b08f-b0966800063a)
![image](https://github.com/Sab1e-GitHub/BadAppleJuice/assets/46400438/1cd9c326-6fcd-4cfd-8e11-410007f18574)

**Comment by Sab1e-dev** [comment]
已经了解到该问题。
造成此问题的原因是：
安卓9或更低版本需要access_coarse_location权限，该问题将会在下一个版本中修复。
感谢您的issue以改进此项目。
