### ISSUE TITLE
小米提示無藍牙連接及藍牙廣播權限

### ISSUE THREAD

**Issue by maxyeh0817** [Sab1e-GitHub/BadAppleJuice#5]
提示無BLUETOOTH_CONNECT,BLUETOOTH_ADVERTISE權限

機型：redmi k20 pro
Miui版本：12.5.6
安卓版本：11

**Comment by Sab1e-dev** [comment]
![微信图片_20231212091541](https://github.com/Sab1e-GitHub/BadAppleJuice/assets/72060564/abf9995d-482c-482d-aa89-72263daff107)

* 请尝试从 系统设置→应用设置→应用管理→“BadAppleJuice”→权限管理 授予此权限，选择“始终允许”，否则软件会提示无权限。

**Comment by Mbensjej** [comment]
> ![微信图片_20231212091541](https://github.com/Sab1e-GitHub/BadAppleJuice/assets/72060564/abf9995d-482c-482d-aa89-72263daff107)
> 
> * 请尝试从 系统设置→应用设置→应用管理→“BadAppleJuice”→权限管理 授予此权限，选择“始终允许”，否则软件会提示无权限。
>

**Comment by ye120829** [comment]
正在信息栏一直 正在获取蓝牙权限 怎么处理？

**Comment by maxyeh0817** [comment]
設定裡沒有連接附近設備的權限

![Screenshot_2023-12-13-17-36-24-835_com miui securitycenter](https://github.com/Sab1e-GitHub/BadAppleJuice/assets/55946517/07f3d609-3c45-4a2a-9f00-f0fafc164758)

**Comment by Sab1e-dev** [comment]
据我推测您的问题与issue#6相同，以下复制自issue#6：

已经了解到造成该问题的原因：
[Android 12 中的新蓝牙权限……](https://developer.android.google.cn/about/versions/12/features/bluetooth-permissions?hl=zh-cn)
Android 12 引入了 [BLUETOOTH_SCAN](https://developer.android.google.cn/reference/android/Manifest.permission?hl=zh-cn#BLUETOOTH_SCAN)、[BLUETOOTH_ADVERTISE](https://developer.android.google.cn/reference/android/Manifest.permission?hl=zh-cn#BLUETOOTH_ADVERTISE) 和 [BLUETOOTH_CONNECT](https://developer.android.google.cn/reference/android/Manifest.permission?hl=zh-cn#BLUETOOTH_CONNECT) 权限，可让您的应用扫描附近的设备，而无需请求位置权限。您的应用必须以 Android 12 为目标平台，才能声明这些权限。
您的安卓版本为Android 11，该问题将会在下一版本修复，感谢您对本项目的帮助！
