### ISSUE TITLE
vivo手机无权限提示 打不开权限

### ISSUE THREAD

**Issue by Mbensjej** [Sab1e-GitHub/BadAppleJuice#6]

**Comment by Mbensjej** [comment]
提示无蓝牙权限 权限中心无蓝牙选项            手机型号：vivot1 系统： orlalnos  安卓11

**Comment by Sab1e-dev** [comment]
BadAppleJuice 应用权限那里有没有“定位”或“附近的权限”？
请给程序授予这两个权限后重试。

![image](https://github.com/Sab1e-GitHub/BadAppleJuice/assets/72060564/d8cf808e-fa3e-41be-a818-880b5aa813ed)

**Comment by Mbensjej** [comment]
> BadAppleJuice 应用权限那里有没有“定位”或“附近的权限”？
> 请给程序授予这两个权限后重试。
> 
> ![image](https://github.com/Sab1e-GitHub/BadAppleJuice/assets/72060564/d8cf808e-fa3e-41be-a818-880b5aa813ed)
> 

没有附近的权限选项

**Comment by Mbensjej** [comment]
> BadAppleJuice 应用权限那里有没有“定位”或“附近的权限”？
> 请给程序授予这两个权限后重试。
> 
> ![image](https://github.com/Sab1e-GitHub/BadAppleJuice/assets/72060564/d8cf808e-fa3e-41be-a818-880b5aa813ed)
> 

没有附近的设备选项

**Comment by Sab1e-dev** [comment]
已经了解到造成该问题的原因：
[Android 12 中的新蓝牙权限……](https://developer.android.google.cn/about/versions/12/features/bluetooth-permissions?hl=zh-cn)
Android 12 引入了 [BLUETOOTH_SCAN](https://developer.android.google.cn/reference/android/Manifest.permission?hl=zh-cn#BLUETOOTH_SCAN)、[BLUETOOTH_ADVERTISE](https://developer.android.google.cn/reference/android/Manifest.permission?hl=zh-cn#BLUETOOTH_ADVERTISE) 和 [BLUETOOTH_CONNECT](https://developer.android.google.cn/reference/android/Manifest.permission?hl=zh-cn#BLUETOOTH_CONNECT) 权限，可让您的应用扫描附近的设备，而无需请求位置权限。您的应用必须以 Android 12 为目标平台，才能声明这些权限。
您的安卓版本为Android 11，该问题将会在下一版本修复，感谢您对本项目的帮助！
