### ISSUE TITLE
一直显示正在获取蓝牙权限

### ISSUE THREAD

**Issue by xuanmingdaoren** [Sab1e-GitHub/BadAppleJuice#7]
开启后显示正在获取蓝牙权限，设置里已经打开了允许访问附近设备，但是还是没用。
无法发送弹窗。

**Comment by Sab1e-dev** [comment]
能否提供相关问题的截图？谢谢！

**Comment by xuanmingdaoren** [comment]
###

**Comment by xuanmingdaoren** [comment]
我好像没有办法发出来图片，选中以后也发不出来。我尽可能描述一下。
在点击Attack以后，在底下显示的字为:正在进行各项检测……检测完毕，功能正常！ 正在获取蓝牙权限……然后显示了一些参数
在这个过程中，获取蓝牙权限并没有后续，没有显示获取成功。同时，也没有成功启动功能，并不能发送弹窗。

**Comment by Sab1e-dev** [comment]
您目前使用的版本是1.5吗？刚更新了1.5版本，应该不会出现这种情况了。

**Comment by xuanmingdaoren** [comment]
更新后可以使用了。
之前没有办法给位置的权限，现在可以给权限了。给完位置权限以后蓝牙就可以正常获取了。
